DROP TABLE MAJOR;
DROP TABLE STUDENT;
CREATE TABLE MAJOR( -- 제약조건을 옆에 기술
    mCODE NUMBER(2) NOT NULL,
    mNAME VARCHAR2(20),
    mOFFICE VARCHAR2(20),
    UNIQUE(mNAME),
    PRIMARY KEY(mCODE)
);
CREATE TABLE STUDENT(
    sNO NUMBER(10) NOT NULL,
    sNAME VARCHAR2(12),
    sSCORE NUMBER(10),
    mCODE NUMBER(2), 
    PRIMARY KEY(sNO),
    CHECK(sSCORE BETWEEN 0 AND 100),
    FOREIGN KEY(mCODE) REFERENCES MAJOR(mCODE)
);
INSERT INTO MAJOR (mCODE, mNAME, mOFFICE) VALUES (1, '컴퓨터공학', 'A101호');
INSERT INTO MAJOR (mCODE, mNAME, mOFFICE) VALUES (2, '빅데이터', 'A102호');
INSERT INTO STUDENT (sNO, sNAME, sSCORE, mCODE) VALUES (101, '홍길동', 99, 1);
INSERT INTO STUDENT (sNO, sNAME, sSCORE, mCODE) VALUES (102, '신길동', 100, 2);
SELECT * FROM MAJOR;
SELECT * FROM STUDENT;
SELECT sNO 학번, sNAME 이름, sSCORE 점수, s.MCODE 학과코드, mNAME 학과명, mOFFICE 학과사무실
    FROM MAJOR M, STUDENT S WHERE M.mCODE = S.mCODE;