-- [IV] DDL, DCL, DML
/* SQL
(1) DCL:
    사용자계정생성 CREATE USER, 권한부여 GRANT
    권한박탈 REVOKE, 사용자계정삭제 DROP USER
    트렌젝션 명령어 ROLLBACK, COMMIT
(2) DDL : 
    테이블생성 CREATE TABLE, 테이블구조변경 ALTER TABLE, 테이블삭제 DROP TABLE
(3) DML : CRUD
    입력 INSERT, 검색 SELECT, 수정 UPDATE, 삭제 DELETE - DML은 취소 가능
*/
--DDL
--1. 테이블생성(CREATE TABLE 테이블명...) : 테이블의 구조를 정의
    -- ORACLE 타입 : NUMBER(38이하의 자릿수), DATE, VARCHAR2(4000이하의 바이트수), CLOB(
CREATE TABLE BOOK(
    BOOKID NUMBER(4), -- BOOKID필드의 타입은 숫자4자리
    BOOKNAME VARCHAR2(20), --BOOKNAME필드의 타입은 문자 20바이트(한글1자=3바이트)
    PUBLISHER VARCHAR2(20),
    RDATE DATE, -- RDATE필드의 타입은 DATE형(날짜+시간)
    PRICE NUMBER(8,2), -- PRICE필드의 타입은 숫자 전제8자리 중 소숫점 2자리
    PRIMARY KEY(BOOKID) -- 제약조건 : BOOKID를 주키(PRIMARY KEY) 필드로
);
SELECT * FROM BOOK;
DESC BOOK;
DROP TABLE BOOK; -- 2. 테이블 삭제(DROP TABLE 테이블명)
CREATE TABLE BOOK(
    BOOKID NUMBER(4) PRIMARY KEY, -- BOOKID필드의 타입은 숫자4자리
    BOOKNAME VARCHAR2(20), --BOOKNAME필드의 타입은 문자 20바이트(한글1자=3바이트)
    PUBLISHER VARCHAR2(20),
    RDATE DATE, -- RDATE필드의 타입은 DATE형(날짜+시간)
    PRICE NUMBER(8,2) -- PRICE필드의 타입은 숫자 전제8자리 중 소숫점 2자리
);
SELECT * FROM EMP;
SELECT * FROM DEPT; -- 10, 20, 30, 40 부서
INSERT INTO EMP VALUES(9999, '홍길동', NULL, NULL, NULL, NULL, NULL, 50);
-- DEPT와 유사한 DEPT01 생성 : DEPTNO(숫2-PK), DNAME(문14), LOC(문13) 
CREATE TABLE DEPT01(
    DEPTNO NUMBER(2),
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13),
    PRIMARY KEY(DEPTNO)
);
INSERT INTO DEPT01 VALUES (10, '전산실', '신림');
SELECT * FROM DEPT01;
ROLLBACK; -- DML 취소
-- EMP와 유사한 EMP01 생성 : EMPNO(숫4-PK), ENAME(문10), HIREDATE(날), SAK(숫7.2), DEPTNO(숫2-FK)
CREATE TABLE EMP01(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    HIREDATE DATE,
    SAL NUMBER(7,2), -- 소숫점앞 5자리 소숫점뒤 2자리. 총 7자리
    PRIMARY KEY(EMPNO),
    DEPTNO NUMBER(2) REFERENCES DEPT01 (DEPTNO) -- 외래키(FOREIGN KEY) 제약조건`
);
DROP TABLE EMP01;
CREATE TABLE EMP01(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    HIREDATE DATE,
    SAL NUMBER(7,2), -- 소숫점앞 5자리 소숫점뒤 2자리. 총 7자리
    DEPTNO NUMBER(2),
    PRIMARY KEY(EMPNO),
    FOREIGN KEY(DEPTNO) REFERENCES DEPT01(DEPTNO)
);
INSERT INTO EMP01 VALUES (1001, '홍길동', SYSDATE, 9999, 10);
COMMIT; -- 트랜젝션 영역에 쌓여 있는 DML명령어들을 ORACLE에 일괄적용
SELECT * FROM EMP01;

-- DML 
-- 1. INSERT INTO 테이블명(필드명1, 필드명2, ...) VALUES(값1, 값2, ..);
    -- INSERT INTO 테이블명 VALUES (값1, 값2, .. 값N);
SELECT * FROM DEPT01;
INSERT INTO DEPT01 VALUES (50, 'ACCOUNTING', 'SEOUL');
INSERT INTO DEPT01 (DEPTNO, LOC, DNAME) VALUES (60, '신림', '개발');
INSERT INTO DEPT01 (DEPTNO, LOC, DNAME) VALUES (70, 'NULL', '영업'); -- 명시적으로 NULL입력
INSERT INTO DEPT01 (DEPTNO, DNAME) VALUES (80,'연구'); -- 묵시적 NULL 입력
-- 서브쿼리를 이용한 INSERT
  -- ex. DEPT테이블의 20~40분서의 내용을 DEPT01테이블에 INSERT
INSERT INTO DEPT01 SELECT * FROM DEPT WHERE DEPTNO>10;

-- PDF 1PAGE 연습문제
-- 테이블 삭제
DROP TABLE SAM01;
-- 테이블 생성
CREATE TABLE SAM01(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    SAL NUMBER(7,2),
    PRIMARY KEY(EMPNO)
);
-- 한행씩 INSERT
INSERT INTO SAM01 VALUES (1000, 'APPLE', 'POLICE', '10000');
INSERT INTO SAM01 VALUES (1010, 'BANANA', 'NURSE', '15000');
INSERT INTO SAM01 VALUES (1020, 'ORANGE', 'DOCTOR', '25000');
INSERT INTO SAM01 VALUES (1030, 'VERY', NULL, '25000');
INSERT INTO SAM01 VALUES (1040, 'CAT', NULL, '2000');
-- 서브쿼리(10번 부서 소속 사원 INSERT)를 이용한 3행 INSERT`
INSERT INTO SAM01 SELECT EMPNO, ENAME, JOB, SAL FROM EMP E,DEPT D WHERE E.DEPTNO = D.DEPTNO AND D.DEPTNO=10;
-- 확인
SELECT * FROM SAM01;
-- 트랜젝션에 쌓여 있는 DML 오라클에 적용
COMMIT;

--2. UPDATE 테이블명 SET 필드명1=값1[, 필드명2=값2, ... 필드명n=값n] [WHERE 조건];
DROP TABLE EMP01;
-- 서브쿼리를 이용한 테이블 생성(제약조건 제외된 데이터만 가져옴)
CREATE TABLE EMP01 AS SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP;
SELECt * FROM EMP01;
    --ex. 부서번호를 30번으로 수정
    UPDATE EMP01 SET DEPTNO=30;
    ROLLBACK;
    -- ex. 모든 사원(EMP01)의 급여(SAL)를 10%인상
    UPDATE EMP01 SET SAL = SAL*1.1;
    SELECT * FROM EMP01;
    ROLLBACK;
    --ex. EMP01테이블의 10번부서의 직원을 30번 부서로
    UPDATE EMP01 SET DEPTNO=30 WHERE DEPTNO=10;
    SELECT * FROM EMP01;
    ROLLBACK;
    --ex. SCOTT의 부서번호를 10으로, JOB은 'MANAGER'로, SAL과 COMM은 500$씩 인상,
        -- 입사일은 오늘로, 상사는 'KING'으로 수정
    UPDATE EMP SET DEPTNO=10,
                JOB= 'MANAGER',
                SAL = SAL+500,
                COMM = NVL(COMM,0)+500,
                HIREDATE = SYSDATE,--지금
                MGR = (SELECT EMPNO FROM EMP WHERE ENAME='KING')
            WHERE ENAME='SCOTT';
    SELECT * FROM EMP;
    ROLLBACK;
    -- ex. 모든 사원의 급여와 입사일을 'KING'의 급여와 입사일로 수정
    UPDATE EMP
        SET SAL = (SELECT SAL FROM EMP WHERE ENAME='KING'),
            HIREDATE = (SELECT HIREDATE FROM EMP WHERE ENAME='KING');
    UPDATE EMP
        SET (SAL, HIREDATE) = (SELECT SAL, HIREDATE FROM EMP WHERE ENAME='KING');
    SELECT * FROM EMP;
    ROLLBACK;
    
-- 3. DELETE FROM 테이블명 [WHERER 조건];
SELECT * FROM EMP01;
ROLLBACK; -- INSERT, UPDATE, DELETE만 취소 가능
DELETE FROM DEPT; -- 불가(EMP테이블의 참조된 데이터가 있어서 DELETE 불가)
    -- ex. EMP01에서 'FORD' 직원 퇴사
    DELETE FROM EMP01 WHERE ENAME='FORD';
    -- ex. EMP01에서 30번 부서 직원을 삭제
    DELETE FROM EMP01 WHERE DEPTNO=30;
    -- ex 부서명이 RESEARCH 부서인 직원을 삭제
    DELETE FROM EMP01 WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME='RESEARCH');
    -- ex. SAM01테이블에서 JOB이 정해지지 않은 사원 삭제
    DELETE FROM SAM01 WHERE JOB IS NULL;
    SELECT * FROM SAM01;
    -- ex SAM01테이블에서 이름이 ORANGE인 데이터 삭제
    DELETE FROM SAM01 WHERE ENAME='ORANGE';

-- 제약조선
-- (1) PRIMARY KEY : 테이블의 각 행을 유일한 값으로 식별하기 위한 필드
-- (2) FOREIGN KEY : 테이블의 열이 다른 테이블의 열을 참조
-- (3) NOT NULL : NULL을 포함하지 않는다
-- (4) UNIQUE : 모든 행의 값이 유일해야. NULL값은 허용(NULL은 여러개 가능)
-- (5) CHECK(조건) : 해당 조건이 만족(NULL값 허용)
-- DEFAULT 기본값: 기본값 설정(해당 열의 데이테를 입력하지 않고 INSERT하면 NULL이 들어갈 것을 DEFAULT값이 들어가도록)

--DEPT1 & EMP1 테이블생성
CREATE TABLE DEPT1( -- 제약조건을 옆에 기술
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME VARCHAR2(14) NOT NULL UNIQUE,
    LOC VARCHAR2(13) NOT NULL
);
CREATE TABLE EMP1(
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(20) NOT NULL,
    JOB VARCHAR2(20) NOT NULL,
    MGR NUMBER(4),
    HIREDATE DATE DEFAULT SYSDATE,
    SAL NUMBER(7,2) CHECK(SAL>0),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2) REFERENCES DEPT1(DEPTNO)
);
SELECT * FROM DEPT1;
SELECT * FROM EMP1;
DROP TABLE DEPT1;
DROP TABLE EMP1;
CREATE TABLE DEPT1( -- 제약조건을 옆에 기술
    DEPTNO NUMBER(2) ,
    DNAME VARCHAR2(14) NOT NULL,
    LOC VARCHAR2(13) NOT NULL,
    PRIMARY KEY(DEPTNO),
    UNIQUE(DNAME)
);
CREATE TABLE EMP1(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(20) NOT NULL,
    JOB VARCHAR2(20) NOT NULL,
    MGR NUMBER(4),
    HIREDATE DATE DEFAULT SYSDATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2),
    PRIMARY KEY(EMPNO),
    CHECK(SAL>0),
    FOREIGN KEY(DEPTNO) REFERENCES DEPT1(DEPTNO)
);

INSERT INTO DEPT1 SELECT * FROM DEPT;
INSERT INTO DEPT1 VALUES (50, 'SALES', '서울'); -- UNIQUE 에러
INSERT INTO DEPT1 (DEPTNO, DNAME) VALUES (50,'전산'); -- NOT NULL에러
INSERT INTO EMP1 (EMPNO, ENAME, JOB, DEPTNO) VALUES (9001, 'HONG', 'MANAGER', 40);
-- INSERT에서 언급되지 않은 필드는 NULL값으로 입력
SELECT * FROM EMP1 WHERE EMPNO=9001;
INSERT INTO EMP1 (EMPNO, ENAME, JOB, SAL) VALUES (9002, 'KIM', 'MANAGER', -90);
INSERT INTO EMP1 (EMPNO, ENAME, JOB, SAL) VALUES (9002, 'KIM', 'MANAGER', 90);