DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(2) PRIMARY KEY,
    LEVELNAME VARCHAR2(10) NOT NULL
);
CREATE TABLE MEMBER(
    mNO NUMBER(5) PRIMARY KEY,
    mNAME VARCHAR2(20) NOT NULL,
    mPW VARCHAR2(8) NOT NULL,
    mMAIL VARCHAR2(20) UNIQUE,
    mPOINT NUMBER(20) CHECK(mPOINT>=0),
    mRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(2), 
    FOREIGN KEY(LEVELNO) REFERENCES MEMBER_LEVEL(LEVELNO)
);
DROP SEQUENCE MEMBER_MNO_SQ;
CREATE SEQUENCE MEMBER_MNO_SQ MAXVALUE 99999 NOCACHE NOCYCLE;

INSERT INTO MEMBER_LEVEL
    VALUES (-1,'black');
INSERT INTO MEMBER_LEVEL
    VALUES (0,'일반');
INSERT INTO MEMBER_LEVEL
    VALUES (1,'실버');
INSERT INTO MEMBER_LEVEL
    VALUES (2,'골드');

INSERT INTO MEMBER (mNO, mNAME, mPW, mMAIL, mPOINT, mRDATE, LEVELNO)
    VALUES (MEMBER_MNO_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, '24/09/26', 0); 

INSERT INTO MEMBER (mNO, mNAME, mPW, mMAIL, mPOINT, mRDATE, LEVELNO)
    VALUES (MEMBER_MNO_SQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, '22/04/21', 1); 

SELECT mNO , mNAME , mRDATE, mMAIL, mPOINT point, LEVELNAME
  FROM MEMBER M, MEMBER_LEVEL L
  WHERE M.LEVELNO = L.LEVELNO;
